### ISSUE TITLE
Slightly different output depending on position of print() statement within for-loop

### ISSUE THREAD

**Issue by ethan-dee** [ethan-dee/fall2022_python_workshop#1]
If I run this block of code:
```
for n in range(0,1000000):
    print(n)
    if n>100:
        break
```
it will print every integer from 0,...,101, but if I run _this_ block of code:
```
for n in range(0,1000000):
    if n>100:
        break
    print(n)
```
it will print every integer from 0,...,_100_. Why is there this difference?

Also, if I run _this_ block of code:
```
for n in range(0,1000000):
    if n>100:
        break
print(n)
```
it only prints 101. Why?

**Comment by ysu1117** [comment]
First code: Print comes before break. So, 101 is already printed and then break.
Second code: Break comes before print. So, 101 cannot be printed because break comes first.
Third code: Print is outside of a loop. So, during a loop, nothing will be printed. After break, 101 (which is n when a loop breaks) will be printed.

**Comment by ethan-dee** [comment]
Yep, well said! :)
